import type { VoiceRef } from '../voice/VoiceRef';
import type {
  AudioFormat,
  DeliveryDirection,
  MoneyAmount,
  ProviderId,
  RetryPolicy,
} from '../shared/types';

/**
 * NarrationRequest — the provider-neutral narration request model.
 *
 * This is the ONLY shape the narration engine and provider adapters exchange for a
 * synthesis request. Nothing vendor-specific belongs at the top level — vendor-specific
 * tuning goes through `providerOptions`, and the engine never reads from that bag itself.
 *
 * Matches the approved TTS Provider Abstraction Architecture exactly. Do not add fields
 * here without an explicit architecture decision — see providerOptions for the escape hatch.
 */
export interface NarrationRequest {
  /** Idempotency key — generated by the narration engine, unique per invocation. */
  requestId: string;

  bookId: string;
  chapterId: string;
  segmentId: string;

  text: string;
  /** BCP-47, e.g. "en-US" */
  language: string;

  narratorVoice: VoiceRef;
  /** Present only for dialogue segments (Phase 2+). Absent in MVP. */
  characterVoice?: VoiceRef;

  deliveryDirection?: DeliveryDirection;

  output: {
    format: AudioFormat;
    sampleRateHz?: number;
    quality?: 'draft' | 'standard' | 'premium';
  };

  /** Hint only — the engine may override on capability/fallback grounds. */
  providerPreference?: ProviderId;
  /** Hard requirements the engine must route on. */
  requiredCapabilities?: string[];
  retryPolicy?: RetryPolicy;
  /** Abort/fallback if a provider's cost estimate exceeds this. */
  costCeiling?: MoneyAmount;

  /**
   * Provider-specific escape hatch. The engine passes this through untouched — only the
   * matching provider adapter reads its own namespaced block. Never promote a vendor-only
   * concept to a top-level field; if two providers converge on the same concept, it gets
   * promoted into the neutral model instead (see corrections doc §7 discipline).
   */
  providerOptions?: Record<string, Record<string, unknown>>;

  metadata?: Record<string, string>;
}
