import { pgTable, uuid, varchar, timestamp, uniqueIndex, index } from 'drizzle-orm/pg-core';
import { users } from './users.js';

/**
 * sessions — server-side session state. The internal `id` (this table's primary key) is
 * NOT the bearer credential a client presents — it's an ordinary internal row identifier,
 * same as every other table in this schema. The actual credential (`tokenHash`) is a
 * SHA-256 hash of the random raw session token handed to the client at login; the raw
 * token itself is never persisted anywhere.
 *
 * SHA-256 (fast hash), not scrypt (slow/memory-hard hash), is correct here: unlike a
 * user-chosen password (low entropy, needs to resist offline brute-force), a session
 * token is already a high-entropy random value generated by randomBytes — hashing it
 * only needs to prevent the token from being recovered if the database itself leaks,
 * which a fast cryptographic hash already achieves.
 */
export const sessions = pgTable(
  'sessions',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    userId: uuid('user_id')
      .notNull()
      .references(() => users.id),
    /** hex-encoded SHA-256 of the raw bearer token — never the raw token itself */
    tokenHash: varchar('token_hash', { length: 64 }).notNull(),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
  },
  (table) => ({
    tokenHashUnique: uniqueIndex('sessions_token_hash_unique').on(table.tokenHash),
    userIdIdx: index('sessions_user_id_idx').on(table.userId),
    expiresAtIdx: index('sessions_expires_at_idx').on(table.expiresAt),
  }),
);
